version: '3'
services:
  analyzer:
    build: ./analysis
    ports:
      - "5000:5000"
  db:
    image: rethinkdb
    ports:
      - "28015:28015"
      - "8080:8080"
  processor:
    build: ./processor
    environment:
      - GH_API_TOKEN
      - ANALYSIS_DOMAIN=analyzer:5000
      - RDB_HOST=db
      - RDB_PORT=28015
